create_drone="create drone"
get_drone_by_serial_number = "get drone by serial number"
delete_drone_by_serial_number = "delete drone by serial number"
get_all_drones = "get all drones"
change_drone = "change drone settings"